workflows:
  version: 2
  context: org-global
  build-image:
    jobs:
      build:
        branches:
          only:
            - master
            - develop
        machine: true
        working_directory: ~/app
        environment:
          APP_NAME: keycloak
        steps:
          - checkout
    #      - run: sudo service docker stop
    #      - run: curl -fsSL https://get.docker.com/ | sudo sh
          - run:
              name: Build
              when: on_success
              command: docker-compose -f docker-build.yml build prod
          - run:
              name: Authenitcate Docker Hub
              when: on_success
              command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
          - deploy:
              name: Push to Docker Hub
              when: on_success
              command: |
                if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  docker tag ${APP_NAME}:prod ${DOCKER_USER}/${APP_NAME}:${CIRCLE_TAG}
                fi
          - deploy:
              name: Push to Docker Hub
              when: on_success
              command: |
                if [ "${CIRCLE_BRANCH}" == "develop" ]; then
                  docker tag $APP_NAME:prod $DOCKER_USER/$APP_NAME:dev
                fi
