version: 2

jobs:
  some_name:
    machine:
      enabled: true
    working_directory: ~/app
    environment:
      APP_NAME: keycloak
    steps:
      - checkout
      - run: echo ${CIRCLE_BRANCH}
      - run:
          name: Build
          when: on_success
          command: docker-compose -f docker-build.yml build prod
      - run:
          name: Authenitcate Docker Hub
          when: on_success
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - deploy:
          name: Push to Docker Hub
          when: on_success
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag ${APP_NAME}:prod ${DOCKER_USER}/${APP_NAME}:${CIRCLE_TAG}
            fi
      - deploy:
          name: Push to Docker Hub
          when: on_success
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              docker tag $APP_NAME:prod $DOCKER_USER/$APP_NAME:dev
            fi

workflows:
  version: 2

  build_image:
    jobs:
      - some_name
