version: 2

jobs:
  build_tagged_release:
    machine:
      enabled: true
    working_directory: ~/app
    environment:
      APP_NAME: keycloak
    steps:
      - checkout
      - run:
          name: Build
          when: on_success
          name: Authenitcate Docker Hub
          when: on_success
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - deploy:
          name: Tag and Push to Docker Hub
          when: on_success
          command: |
            docker tag ${APP_NAME}:prod ${DOCKER_USER}/${APP_NAME}:${CIRCLE_TAG}
            docker push ${DOCKER_USER}/${APP_NAME}:${CIRCLE_TAG}

  build_dev:
    machine:
      enabled: true
    working_directory: ~/app
    environment:
      APP_NAME: keycloak
    steps:
      - checkout
      - run:
          name: Build
          when: on_success
          command: docker-compose -f docker-build.yml build prod
      - run:
          name: Authenitcate Docker Hub
          when: on_success
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - deploy:
          name: Tag and Push to Docker Hub
          when: on_success
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              docker tag ${APP_NAME}:prod ${DOCKER_USER}/${APP_NAME}:dev
              docker push ${DOCKER_USER}/${APP_NAME}:dev
            fi

workflows:
  version: 2

  build_and_push_image:
    jobs:
      - build_tagged_release:
          filters:
            tags:
              only: /.*/
      - build_dev:
          filters:
            branches:
              only: develop
